parameters:

- name: jobName
  type: string

- name: displayName
  type: string

- name: pool
  type: object

- name: container
  type: string

- name: timeoutInMinutes
  type: number

- name: branch
  type: string

- name: os
  type: string
  values:
  - win
  - linux
  - osx
  - rhel.6

- name: arch
  type: string
  values:
  - arm
  - arm64
  - x64
  - x86

- name: unitTests
  type: boolean

- name: functionalTests
  type: boolean

- name: codeCoverage
  type: boolean

- name: componentDetection
  type: boolean

- name: sign
  type: boolean

- name: verifySigning
  type: boolean

- name: publishArtifact
  type: boolean

- name: enableADOLogIssue
  type: boolean
  default: false

- name: packageType
  type: string
  default: agent
  values:
  - agent
  - pipelines-agent

jobs:

- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}

  ${{ if ne(parameters.container, '') }}:
    container: ${{ parameters.container }}

  variables:
    PACKAGE_TYPE: ${{ parameters.packageType }}
    ${{ if eq(parameters.os, 'win') }}:
      devCommand: dev.cmd
    ${{ if ne(parameters.os, 'win') }}:
      devCommand: ./dev.sh
    layoutRoot: '_layout/${{ parameters.os }}-${{ parameters.arch }}'

  steps:

  # Component detection
  - ${{ if parameters.componentDetection }}:
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'

  # Clean
  - checkout: self
    clean: true

  # Switch to branch if set
  - ${{ if ne(parameters.branch, '') }}:
    - template: switch-branch.yml
      parameters:
        branch: ${{ parameters.branch }}

  # 1ES images used on the ARM pool doesn't contain unzip tool, so we need to install it before starting the build
  - ${{ if eq(parameters.arch, 'arm64') }}:
    - script: sudo apt-get update && sudo apt-get -y install unzip
      displayName: Install unzip

  # Build agent layout
  - script: ${{ variables.devCommand }} layout Release ${{ parameters.os }}-${{ parameters.arch }}
    workingDirectory: src
    displayName: Build & Layout Release
    ${{ if parameters.enableADOLogIssue }}:
      env:
        ADO_ENABLE_LOGISSUE: true

  # Check if broken symlinks exist in the agent build
  - task: Bash@3.201.1
    inputs:
      filePath: src/Misc/check-symlinks.sh
    displayName: Check symlinks

  # Run l0 tests
  - ${{ if parameters.unitTests }}:
    - script: ${{ variables.devCommand }} testl0 Debug ${{ parameters.os }}-${{ parameters.arch }}
      workingDirectory: src
      displayName: Unit tests

  # Install nuget
  - ${{ if eq(parameters.os, 'win') }}:
    - task: NuGetToolInstaller@1
      displayName: Install NuGet for signing tests

  # Run l1 tests
  - ${{ if parameters.functionalTests }}:
    - ${{ if and(eq(parameters.os, 'win'), eq(parameters.arch, 'x86')) }}:
      - task: UseDotNet@2
        displayName: Install .NET Core 3.1 SDK
        inputs:
          version: '3.1.22'
          packageType: runtime
          performMultiLevelLookup: true
    - script: ${{ variables.devCommand }} testl1 Debug ${{ parameters.os }}-${{ parameters.arch }}
      workingDirectory: src
      displayName: Functional tests

  - ${{ if or(parameters.unitTests, parameters.functionalTests) }}:
    # Publish test results
    - task: PublishTestResults@2
      displayName: Publish Test Results **/*.trx
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Agent Tests - ${{ parameters.os }}-${{ parameters.arch }}'
      condition: always()

    # Upload test log
    - task: PublishBuildArtifacts@1.200.0
      displayName: Publish Test logs
      inputs:
        pathToPublish: src/Test/TestLogs
        artifactName: ${{ parameters.os }}-${{ parameters.arch }}-$(System.JobId)
        artifactType: container
      condition: always()

  # Code coverage
  - ${{ if and(parameters.codeCoverage, parameters.unitTests, parameters.functionalTests) }}:
    - script: dotnet tool install --global dotnet-reportgenerator-globaltool
      displayName: Install Report Generator

    - script: ${{ variables.devCommand }} report
      displayName: Generate Code Coverage report
      workingDirectory: src

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: _reports/**/Cobertura.xml
        pathToSources: src

  - ${{ if eq(parameters.os, 'osx') }}:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.1.x'

  - ${{ if parameters.sign }}:
    # Signing steps
    - template: signing.yml
      parameters:
        layoutRoot: ${{ variables.layoutRoot }}
        isWindows: ${{ eq(parameters.os, 'win') }}

  # Publish artifacts
  - ${{ if parameters.publishArtifact }}:

    # Package .NET Core Windows dependency (VC++ Redistributable)
    - ${{ if eq(parameters.os, 'win') }}:
      - template: package-vcredist.yml
        parameters:
          layoutRoot: ${{ variables.layoutRoot }}
          flavor: ${{ parameters.arch }}

    # Create agent package zip
    - script: "${{ variables.devCommand }} package Release ${{ parameters.os }}-${{ parameters.arch }}"
      workingDirectory: src
      displayName: Package Release

    - script: "${{ variables.devCommand }} hash Release ${{ parameters.os }}-${{ parameters.arch }}"
      workingDirectory: src
      displayName: Hash Package

    # Upload agent package zip as build artifact
    - task: PublishBuildArtifacts@1.200.0
      displayName: Publish Artifact
      inputs:
        pathToPublish: _package
        artifactName: agent
        artifactType: container

    # Publish agent package hash too
    - task: PublishBuildArtifacts@1.200.0
      displayName: Publish Artifact
      inputs:
        pathToPublish: _package_hash
        artifactName: hash
        artifactType: container

  # Signing verification
  - ${{ if parameters.verifySigning }}:

    # Verify all binaries are signed (generate report)
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-codesignvalidation.CodesignValidation@0
      displayName: 'Generate Codesign Report'
      inputs:
        path: ${{ variables.layoutRoot }}

    # Verify all binaries are signed (check report)
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
      displayName: 'Verify Codesign Report'
      inputs:
        CodesignValidation: true
        CodesignValidationBreakOn: WarningAbove
        ToolLogsNotFoundAction: Error
