parameters:
- name: branch
  type: string

steps:
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - script: |
      git config user.email "azure-pipelines-bot@microsoft.com"
      git config user.name "azure-pipelines-bot"
      git checkout -f origin/${{ parameters.branch }}
    displayName: Checkout branch
