name: 'LEGO automerge'

on:
  pull_request:
    types:
      - opened
    branches:
      - Localization

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'csigs'
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: enhancement
              
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
